### ISSUE TITLE
Implementation of chrome.hid.receive is outdated

### ISSUE THREAD

**Issue by cgudrian** [dart-gde/chrome.dart#218]
According to [the docs](https://developer.chrome.com/apps/hid#method-receive) `chrome.hid.receive` no longer expects the `size` parameter.

**Comment by adambender** [comment]
Hey there, we have been in the process of migrating our tooling over to support the new git repo (from svn).  I will see how easy it is to get a fix for this quickly.

**Comment by cgudrian** [comment]
The IDL has already been updated: https://codereview.chromium.org/413913003

**Comment by adambender** [comment]
I have pushed 0.7.0-dev1 which should fix this.

**Comment by cgudrian** [comment]
Thanks!
