### ISSUE TITLE
chrome.usb has a timeout parameter in GenericTransferInfo (since Chrome 43)

### ISSUE THREAD

**Issue by bugblat** [dart-gde/chrome.dart#229]
timeout is an optional integer in GenericTransferInfo. It's pretty useful to stop the whole app seizing up if something strange happens to the USB device. Strange couplings and uncouplings may be covered by the Chrome USB handler, but who knows and implementing the timeout in the API could easily catch some corner cases. 

Here's the Chrome docs:
https://developer.chrome.com/apps/usb#type-GenericTransferInfo

**Comment by adambender** [comment]
The last update we did was to chrome 41 and it looks like this was introduced in chrome 43. I think all we will need to do is re-roll. I think we can get this done next week.

**Comment by bugblat** [comment]
That's quick! Many thanks.

**Comment by bholtz** [comment]
We started the process last week and should have it done in the next couple days.

**Comment by bholtz** [comment]
Sorry, this re-roll is looking a little dicier than anticipated. Not done yet, but still working on it.

**Comment by bholtz** [comment]
Sorry again for the delay. Our code generator is a little unhappy with the latest Chrome specs, so repairs are in progress.

**Comment by bholtz** [comment]
It took some time, but it is done! Going to start on the next update this week :)
