### ISSUE TITLE
Error while invoking chrome.system.storage.getInfo

### ISSUE THREAD

**Issue by Kleak** [dart-gde/chrome.dart#230]
I have this error when i invoke chrome.system.storage.getInfo but get well the list of object.

Uncaught Uncaught Error: Error evaluating expression 'freeSpace': NoSuchMethodError: method not found: 'get$freeSpace'

However i have another error when I call chrome.system.storage.getAvailableCapacity and this one stop completely the function

**Comment by adambender** [comment]
Regarding the freeSpace call. I dont see this in our generated API and I also dont see it in the published native js API (https://developer.chrome.com/apps/system_storage#type-StorageUnitInfo). Did you see an example somewhere that suggested such a call existed?

As for the second error, it looks like getAvailableCapacity is only enabled in the Dev Channel (https://developer.chrome.com/apps/system_storage#method-getAvailableCapacity). Can you confirm if you are running Chrome in the Dev Channel?

**Comment by Kleak** [comment]
Have you try to call chrome.aystem.storage.getInfo?
I have search it too and not found it :/ but the error is here

For the second one i haven't seen that it's only on the dev channel

**Comment by adambender** [comment]
Can you confirm the version of the library you are using?

**Comment by Kleak** [comment]
The version is use right now is : 0.7.0-dev1

**Comment by adambender** [comment]
I just tested this at 0.7.0-dev1 and chrome.system.storage.getInfo works as expected by returning a list of StorageUnitInfos. I dont see any invocations related to 'get freeSpace'. Do you have a simple repro of the issue?

**Comment by Kleak** [comment]
Oups sorry it's all my fault...
The error come from my code.
