### ISSUE TITLE
Return type of contentWindow is wrong

### ISSUE THREAD

**Issue by DanielJoyce** [dart-gde/chrome.dart#235]
Iine 564 of gen/app.dart

  Window get contentWindow => _createWindow(jsProxy['contentWindow']);
  set contentWindow(Window value) => jsProxy['contentWindow'] = jsify(value);

Dart analyzer thinks the type of contentWindow is Window from gen/windows.dart when it really should be Window from dart:html

From the chrome.windows api docs:

Window | contentWindow | The JavaScript 'window' object for the created child.

This would the html window object.

**Comment by adambender** [comment]
This is an interesting one because the idls for the window api actually do define a new Window object type. Reading the api docs Im inclined to agree with your interpretation, however, when I run chrome.app.window.getAll() in a simple js-only app I get back a single AppWindow (constructor is called AppWindow) which is decidedly not the same as the global window object.  So it sounds to me like the documentation doesnt quite match the implementation. 

Now having said that, the more important question is, is there something you need the window api to do that it currently doesnt support?

We generally stick to strictly translating the idl's but we can look into little tweaks here or there it if there is a compelling reason.

**Comment by DanielJoyce** [comment]
I don't understand why you are bringing up getAll, because per API it returns ALL appWindows, not content Windows. 

https://developer.chrome.com/apps/app_window#method-getAll

getAll
array of AppWindow chrome.app.window.getAll() <= Returns [AppWindow,...], not Window

That behaviour is expected, docs explicitly say it returns AppWindow, not js ocument window. I need the root js document window so I can get the document

contentWindow is explicitly called out in the docs as returning the js content Window, not a AppWindow.

https://developer.chrome.com/apps/app_window#type-AppWindow

I think the docs are pretty clear.

**Comment by DanielJoyce** [comment]
The problem is what chrome.window is calling Window is reall AppWindow, not Window.

**Comment by DanielJoyce** [comment]
Okay, sorry about this. Here is the problem

chrome.window returns this class:

class Window extends ChromeObject {
  Window({int id, bool focused, int top, int left, int width, int height, List<Tab> tabs, bool incognito, String type, String state, bool alwaysOnTop, String sessionId}) {
    if (id != null) this.id = id;
    if (focused != null) this.focused = focused;
    if (top != null) this.top = top;
    if (left != null) this.left = left;
    if (width != null) this.width = width;
    if (height != null) this.height = height;
    if (tabs != null) this.tabs = tabs;
    if (incognito != null) this.incognito = incognito;
    if (type != null) this.type = type;
    if (state != null) this.state = state;
    if (alwaysOnTop != null) this.alwaysOnTop = alwaysOnTop;
    if (sessionId != null) this.sessionId = sessionId;
  }

From lib/gen/window.dart which is basically useless....

When according to the docs, it should I think return js content Window objects, which are dart:html window objects on the dart side.

The Window object above is basically useless.

**Comment by DanielJoyce** [comment]
Scratch that. Who knows. The API on the javascript side is terribly confusing. I just want to know how to get another window opened in a chrome and talk to the dom inside it.

Apparently its somehow Window => Window ( not root js window object ) => Poorly documented steps => Tabs??? ( who knows ) => ????

**Comment by adambender** [comment]
Yea, the docs arent as straight forward as the could be. Are you building a chrome app or chrome extension? Im pretty sure that chrome apps can only open windows but cannot directly touch the dom contained. They can communicate with pages using postMessage but have no direct access.

**Comment by adambender** [comment]
I want to clarify that when I say 'open windows' Im referring to browser tabs. You can of course open as many appwindows as you want and do what ever you want there.

**Comment by zoechi** [comment]
Window is completely broken and messed up in dart:html. I guess the best way would be to use dart-js-interop if you need to open and communicate with a window here as well.

**Comment by adambender** [comment]
I'm not sure we are in a position to do much about this given the underlying apis, any objection to closing this issue?

**Comment by DanielJoyce** [comment]
Close away.

On Wed, Aug 26, 2015 at 8:26 PM Adam Bender <notifications@github.com>
wrote:

> I'm not sure we are in a position to do much about this given the
> underlying apis, any objection to closing this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-gde/chrome.dart/issues/235#issuecomment-135275194>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.
