### ISSUE TITLE
Chrome.USB throws exception when used in front-end Angular web-application

### ISSUE THREAD

**Issue by basevers** [dart-gde/chrome.dart#262]
Im trying to use chrome.usb API in a angular-4 dart web-application. But it keeps throwing an exception as _usb is null.

For example, `chrome.usb.available` returns false. Or any other api fails as: 
`if (_usb == null) _throwNotAvailable();`

Not sure if we do something wrong or misunderstood how to use chrome.usb api, and therefor first asked [StackOverFlow](https://stackoverflow.com/questions/48896786/dart-chrome-usb-throws-exception-when-used-in-front-end-angular-web-application) for sugestions.

As a workaround, we created a wrapper around a javascript library, this allowed us to move forward. But it would be nice if we could use  chrome.usb API

**Comment by basevers** [comment]
It seems chrome.usb seems to be deprecated.

**Comment by adambender** [comment]
Yea, sorry about that :(

If it gets added back we will definitely make sure it works!
