### ISSUE TITLE
integrate `webview` wrapper

### ISSUE THREAD

**Issue by ghost** [dart-gde/chrome.dart#48]
This one can be assigned to me, as I have an existing package to wrap the `<webview>` element in Dart:

http://pub.dartlang.org/packages/webview

I would happily deprecate that package and get it into here, where it most likely belongs :) 

One possible roadblock at the moment is that it has an accompanying javascript file that it needs (lib/webview.js).  Said javascript can be added explicitly to a user's html or automatically injected by the library (works very much like the js interop library in this regard).  So any examples / tests that use the webview library need to copy the script or rely on the `packages/` links, which don't work in Chrome on most OSes presently...

I thought I'd throw this in the backlog here to get comments, keep track of it.  I could integrate it sooner (with the above caveat) or later (once the whole bartender / resource management solution lands in the Dart ecosystem).

cheers,

**Comment by HannesRammer** [comment]
so do you know if the webview tag is propper supported now, since I seem to have problems using it..  and since webview is asaik chrome only.. should therere not be something from within this package??

or how would I combine webview tag and this package.. currently I am working with the 
https://github.com/HannesRammer/webview

**Comment by rmsmith** [comment]
I think its important to understand that `<webview>` is just an Element (written in Javascript), so working with it in Dart should be the same as with other Javascript custom elements (with the addition that it is only available in the Chrome App context).  In terms of where it may belong best in terms of the wrapper API I'm not sure, but if you do end up working more on the fork of the `webview` package I'd be delighted to see it have a new home - so please ping me if you get to a point where you'd like the `pub` for it :)  I don't use this element anymore in my project so the `webview` package is quite a bit outdated, but I don't know of any fundamental changes that prevent it from working.
